package Vista;

import Controlador.Controlador;
import Controlador.ControladorClientes;
import Controlador.ControladorProductos;
import Controlador.ControladorProveedor;
import Controlador.ControladorUsuarios;

import Modelo.Clientes;
import Modelo.Productos;
import Modelo.Proveedores;
import Modelo.Usuarios;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

public class VistaAdmin extends javax.swing.JFrame {

    // Instanciar los controladores
    Controlador controlador = new Controlador();
    ControladorClientes controladorClientes = new ControladorClientes();
    ControladorProductos controladorProductos = new ControladorProductos();
    ControladorProveedor controladorProveedor = new ControladorProveedor();
    ControladorUsuarios controladorUsuarios = new ControladorUsuarios();

    // Listas
    List<Clientes> listaClientes = controladorClientes.obtenerClientes();
    List<Productos> listaProductos = controladorProductos.obtenerProductos();
    List<Proveedores> listaProveedores = controladorProveedor.obtenerProveedores();
    List<Usuarios> listaUsuarios = controladorUsuarios.obtenerUsuarios();

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();

        // Cargar los datos a las tablas
        mostrarProveedoresEnTabla(listaProveedores);
        mostrarClientesEnTabla(listaClientes);
        mostrarUsuariosEnTabla(listaUsuarios);
        mostrarProductosEnTabla(listaProductos);

        // Cargar los cargos en el comboBox
        controladorUsuarios.cargarCargos(jComboBoxCargo);
        controladorProductos.cargarCategorias(comboBoxStock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        VistaAdministrador = new javax.swing.JTabbedPane();
        Panelinicio = new javax.swing.JPanel();
        PanelTablaProveedores = new javax.swing.JScrollPane();
        TablaListaProveedores = new javax.swing.JTable();
        TxtProveedores = new javax.swing.JLabel();
        PanelTablaProductos = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        TxtRegistroVentas = new javax.swing.JLabel();
        PanelListaDeClientes = new javax.swing.JScrollPane();
        TablaListaClientes = new javax.swing.JTable();
        TxtListaCliente = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelPersonal = new javax.swing.JPanel();
        TxtTitulo = new javax.swing.JLabel();
        LabelNombrePersonal = new javax.swing.JLabel();
        LabelRut = new javax.swing.JLabel();
        LabelContacto = new javax.swing.JLabel();
        LabelCargo = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        TxtNombreUsuario = new javax.swing.JTextField();
        TxtRutUsuario = new javax.swing.JTextField();
        TxtClaveUsuario = new javax.swing.JTextField();
        TxtCorreoUsuario = new javax.swing.JTextField();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        BtnAgregarUsuario = new javax.swing.JButton();
        BtnEliminarUsuario = new javax.swing.JButton();
        BtnModificarUsuario = new javax.swing.JButton();
        PanelTablaPersonal = new javax.swing.JPanel();
        ScrollTablaPersonal = new javax.swing.JScrollPane();
        TablaPersonal = new javax.swing.JTable();
        PanelProductos = new javax.swing.JPanel();
        LabelIngresoProductos = new javax.swing.JLabel();
        LabelNombreProducto = new javax.swing.JLabel();
        LabelProveedor = new javax.swing.JLabel();
        LabelStockProducto = new javax.swing.JLabel();
        LabelPrecioUnitario = new javax.swing.JLabel();
        BtnAgregarProducto = new javax.swing.JButton();
        BtnEliminarProducto = new javax.swing.JButton();
        BtnModificarProducto = new javax.swing.JButton();
        TxtNombreProducto = new javax.swing.JTextField();
        TxtStockProducto = new javax.swing.JTextField();
        TxtPrecioUnitario = new javax.swing.JTextField();
        ScrollTablaProductos = new javax.swing.JScrollPane();
        TablaProductos1 = new javax.swing.JTable();
        comboBoxStock = new javax.swing.JComboBox<>();
        PanelClientes = new javax.swing.JPanel();
        LabelRegistroClientes = new javax.swing.JLabel();
        LabelNombreCliente = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        LabelContactoCliente = new javax.swing.JLabel();
        LabelCorreoCliente = new javax.swing.JLabel();
        TxtNombreCliente = new javax.swing.JTextField();
        TxtRutCliente = new javax.swing.JTextField();
        TxtContactoCliente = new javax.swing.JTextField();
        TxtCorreoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRegistroClientes = new javax.swing.JTable();
        BtnAgregarCliente = new javax.swing.JButton();
        BtnEliminarCliente = new javax.swing.JButton();
        BtnModificarCliente = new javax.swing.JButton();
        PanelProveedores = new javax.swing.JPanel();
        LabelRegistroProveedores = new javax.swing.JLabel();
        LabelNombreProveedores = new javax.swing.JLabel();
        LabelEmpresa = new javax.swing.JLabel();
        LabelContactoProveedor = new javax.swing.JLabel();
        LabelCorreoProveedor = new javax.swing.JLabel();
        TxtNombreProveedor = new javax.swing.JTextField();
        TxtEmpresa = new javax.swing.JTextField();
        TxtContactoProveedor = new javax.swing.JTextField();
        TxtCorreoProveedor = new javax.swing.JTextField();
        ScrollTablaProveedores = new javax.swing.JScrollPane();
        TablaRegistroProveedor = new javax.swing.JTable();
        BtnEliminarProveedor = new javax.swing.JButton();
        BtnModificarProveedor = new javax.swing.JButton();
        btnAgregarProveedor = new javax.swing.JButton();
        PanelRegistroDeVentas = new javax.swing.JPanel();
        LabelRegistroDeVentas = new javax.swing.JLabel();
        ScrollTablaVentas = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        LabelProducto = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        LabelCantidad = new javax.swing.JLabel();
        LabelFecha = new javax.swing.JLabel();
        TxtProducto = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        TxtCantidad = new javax.swing.JTextField();
        BtnAgregarVenta = new javax.swing.JButton();
        CBXFecha = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VistaAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TablaListaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Empresa ", "Contacto", "Correo"
            }
        ));
        PanelTablaProveedores.setViewportView(TablaListaProveedores);

        TxtProveedores.setText("              Lista De Proveedores");

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Fecha"
            }
        ));
        PanelTablaProductos.setViewportView(TablaProductos);

        TxtRegistroVentas.setText("Registro De Ventas");

        TablaListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Contacto", "Correo"
            }
        ));
        PanelListaDeClientes.setViewportView(TablaListaClientes);

        TxtListaCliente.setText("Lista De Clientes ");

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelinicioLayout = new javax.swing.GroupLayout(Panelinicio);
        Panelinicio.setLayout(PanelinicioLayout);
        PanelinicioLayout.setHorizontalGroup(
            PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelinicioLayout.createSequentialGroup()
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelinicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelTablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelListaDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(PanelinicioLayout.createSequentialGroup()
                        .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelinicioLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(TxtProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)
                                .addComponent(TxtListaCliente))
                            .addGroup(PanelinicioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(PanelinicioLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(TxtRegistroVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReporte)
                        .addGap(53, 53, 53)))
                .addContainerGap())
        );
        PanelinicioLayout.setVerticalGroup(
            PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelinicioLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtListaCliente)
                    .addComponent(TxtProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelListaDeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(PanelTablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtRegistroVentas)
                    .addComponent(btnReporte)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VistaAdministrador.addTab("Inicio ", Panelinicio);

        TxtTitulo.setText("Registro De Personal");

        LabelNombrePersonal.setText("Nombre");

        LabelRut.setText("Rut");

        LabelContacto.setText("PIN");

        LabelCargo.setText("Cargo");

        LabelCorreo.setText("Correo");

        TxtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreUsuarioActionPerformed(evt);
            }
        });

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona cargo" }));
        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });

        BtnAgregarUsuario.setText("Agregar");
        BtnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarUsuarioActionPerformed(evt);
            }
        });

        BtnEliminarUsuario.setText("Eliminar");
        BtnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarUsuarioActionPerformed(evt);
            }
        });

        BtnModificarUsuario.setText("Modificar");
        BtnModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTablaPersonalLayout = new javax.swing.GroupLayout(PanelTablaPersonal);
        PanelTablaPersonal.setLayout(PanelTablaPersonalLayout);
        PanelTablaPersonalLayout.setHorizontalGroup(
            PanelTablaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        PanelTablaPersonalLayout.setVerticalGroup(
            PanelTablaPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        TablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Rut", "Cargo", "Correo"
            }
        ));
        ScrollTablaPersonal.setViewportView(TablaPersonal);

        javax.swing.GroupLayout PanelPersonalLayout = new javax.swing.GroupLayout(PanelPersonal);
        PanelPersonal.setLayout(PanelPersonalLayout);
        PanelPersonalLayout.setHorizontalGroup(
            PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonalLayout.createSequentialGroup()
                .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonalLayout.createSequentialGroup()
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonalLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(BtnModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPersonalLayout.createSequentialGroup()
                                .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LabelCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelPersonalLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelRut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelNombrePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelContacto)
                                            .addComponent(LabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(TxtRutUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(TxtClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(jComboBoxCargo, 0, 1, Short.MAX_VALUE))
                                    .addComponent(TxtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPersonalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnAgregarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminarUsuario)
                        .addGap(36, 36, 36)))
                .addComponent(ScrollTablaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTablaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(PanelPersonalLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPersonalLayout.setVerticalGroup(
            PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonalLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonalLayout.createSequentialGroup()
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombrePersonal)
                            .addComponent(TxtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelRut)
                            .addComponent(TxtRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelContacto)
                            .addComponent(TxtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCargo)
                            .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCorreo)
                            .addComponent(TxtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(PanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAgregarUsuario)
                            .addComponent(BtnEliminarUsuario))
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificarUsuario))
                    .addComponent(PanelTablaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollTablaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VistaAdministrador.addTab("Registro De Personal", PanelPersonal);

        LabelIngresoProductos.setText("Ingreso De Productos ");

        LabelNombreProducto.setText("Nombre");

        LabelProveedor.setText("Categoria");

        LabelStockProducto.setText("Stock");

        LabelPrecioUnitario.setText("Precio Unitario");

        BtnAgregarProducto.setText("Agregar");
        BtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProductoActionPerformed(evt);
            }
        });

        BtnEliminarProducto.setText("Eliminar");

        BtnModificarProducto.setText("Modificar");
        BtnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarProductoActionPerformed(evt);
            }
        });

        TxtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreProductoActionPerformed(evt);
            }
        });

        TablaProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Categoria", "Stock", "Precio Unitario"
            }
        ));
        ScrollTablaProductos.setViewportView(TablaProductos1);

        comboBoxStock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminarProducto))
                    .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelProductosLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(LabelIngresoProductos))
                        .addGroup(PanelProductosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LabelStockProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(LabelNombreProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelProductosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(LabelPrecioUnitario)
                            .addGap(18, 18, 18)
                            .addComponent(TxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelProductosLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(BtnModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(ScrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelIngresoProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreProducto)
                            .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelProveedor)
                            .addComponent(comboBoxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStockProducto)
                            .addComponent(TxtStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPrecioUnitario)
                            .addComponent(TxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEliminarProducto)
                            .addComponent(BtnAgregarProducto))
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificarProducto))
                    .addComponent(ScrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        VistaAdministrador.addTab("Stock De Productos", PanelProductos);

        LabelRegistroClientes.setText("Registro Clientes");

        LabelNombreCliente.setText("Nombre");

        LabelDireccion.setText("Rut");

        LabelContactoCliente.setText("Celular");

        LabelCorreoCliente.setText("Correo");

        TxtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreClienteActionPerformed(evt);
            }
        });

        TablaRegistroClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre ", "Direccion", "Contacto", "Correo"
            }
        ));
        jScrollPane1.setViewportView(TablaRegistroClientes);

        BtnAgregarCliente.setText("Agregar");
        BtnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarClienteActionPerformed(evt);
            }
        });

        BtnEliminarCliente.setText("Eliminar");
        BtnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClienteActionPerformed(evt);
            }
        });

        BtnModificarCliente.setText("Modificar");

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(BtnAgregarCliente)
                        .addGap(41, 41, 41)
                        .addComponent(BtnEliminarCliente)
                        .addGap(30, 30, 30)
                        .addComponent(BtnModificarCliente))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(LabelRegistroClientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelCorreoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(LabelContactoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtRutCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtContactoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCorreoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addComponent(LabelNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LabelRegistroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreCliente)
                            .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDireccion)
                            .addComponent(TxtRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelContactoCliente)
                            .addComponent(TxtContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCorreoCliente)
                            .addComponent(TxtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarCliente)
                    .addComponent(BtnEliminarCliente)
                    .addComponent(BtnModificarCliente))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        VistaAdministrador.addTab("Registro Clientes", PanelClientes);

        LabelRegistroProveedores.setText("Registro Proveedores");

        LabelNombreProveedores.setText("Nombre");

        LabelEmpresa.setText("Empresa");

        LabelContactoProveedor.setText("Contacto");

        LabelCorreoProveedor.setText("Correo");

        TablaRegistroProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Empresa", "Contacto", "Correo"
            }
        ));
        ScrollTablaProveedores.setViewportView(TablaRegistroProveedor);

        BtnEliminarProveedor.setText("Eliminar");
        BtnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarProveedorActionPerformed(evt);
            }
        });

        BtnModificarProveedor.setText("Modificar");
        BtnModificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarProveedorActionPerformed(evt);
            }
        });

        btnAgregarProveedor.setText("Agregar");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProveedoresLayout = new javax.swing.GroupLayout(PanelProveedores);
        PanelProveedores.setLayout(PanelProveedoresLayout);
        PanelProveedoresLayout.setHorizontalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelNombreProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelContactoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(LabelCorreoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(ScrollTablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(LabelRegistroProveedores))
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnAgregarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminarProveedor)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificarProveedor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelProveedoresLayout.setVerticalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRegistroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNombreProveedores)
                            .addComponent(TxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelEmpresa)
                            .addComponent(TxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelContactoProveedor)
                            .addComponent(TxtContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCorreoProveedor)))
                    .addComponent(ScrollTablaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminarProveedor)
                    .addComponent(BtnModificarProveedor)
                    .addComponent(btnAgregarProveedor))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        VistaAdministrador.addTab("Registro Proveedores", PanelProveedores);

        LabelRegistroDeVentas.setText("Registro De Ventas");

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Fecha"
            }
        ));
        ScrollTablaVentas.setViewportView(TableVentas);

        LabelProducto.setText("Producto");

        LabelPrecio.setText("Precio");

        LabelCantidad.setText("Cantidad");

        LabelFecha.setText("Fecha");

        BtnAgregarVenta.setText("Agregar");
        BtnAgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarVentaActionPerformed(evt);
            }
        });

        CBXFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout PanelRegistroDeVentasLayout = new javax.swing.GroupLayout(PanelRegistroDeVentas);
        PanelRegistroDeVentas.setLayout(PanelRegistroDeVentasLayout);
        PanelRegistroDeVentasLayout.setHorizontalGroup(
            PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollTablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelProducto)
                                    .addComponent(LabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(LabelRegistroDeVentas)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroDeVentasLayout.createSequentialGroup()
                                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBXFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(88, 88, 88))))))
                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(BtnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelRegistroDeVentasLayout.setVerticalGroup(
            PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelRegistroDeVentas)
                .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelCantidad)
                            .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelProducto))))
                .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFecha)
                            .addComponent(CBXFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRegistroDeVentasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelRegistroDeVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelPrecio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollTablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        VistaAdministrador.addTab("Registro De Ventas", PanelRegistroDeVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VistaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VistaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreUsuarioActionPerformed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    private void TxtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreProductoActionPerformed

    private void TxtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtProveedorActionPerformed

    private void BtnAgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgregarVentaActionPerformed

    private void BtnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarProveedorActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaRegistroProveedor.getModel();

        int fila = TablaRegistroProveedor.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun proveedor en la tabla");
            return;
        }
        
        // Eliminar el cliente de la base de datos
        try {
            if (fila != -1) {
                String nombreProveedor = TablaRegistroProveedor.getValueAt(fila, 0).toString();
                String empresaProveedor = TablaRegistroProveedor.getValueAt(fila, 1).toString();
                String celularProveedor = TablaRegistroProveedor.getValueAt(fila, 2).toString();
                String correoProveedor = TablaRegistroProveedor.getValueAt(fila, 3).toString();

                // Crear objeto proveedor
                Proveedores proveedor = new Proveedores();
                proveedor.setNombre(nombreProveedor);
                proveedor.setEmpresa(empresaProveedor);
                proveedor.setCelular(celularProveedor);
                proveedor.setCorreo(correoProveedor);

                // Eliminar proveedor de la base de datos
                controladorProveedor.eliminarProveedor(proveedor);  

                // Eliminar proveedor de la tabla
                modelo.removeRow(fila);                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el proveedor " + e.getMessage());
        }

        listaProveedores = controladorProveedor.obtenerProveedores();
        mostrarProveedoresEnTabla(listaProveedores);
    }//GEN-LAST:event_BtnEliminarProveedorActionPerformed

    private void TxtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreClienteActionPerformed

    private void BtnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarClienteActionPerformed
        // Validar los campos
        if (!validarCamposClientes()) {
            return;
        }

        // Obtener los datos de los campos
        String nombreCliente = TxtNombreCliente.getText();
        String rutCliente = TxtRutCliente.getText();
        String celularCliente = TxtContactoCliente.getText();
        String correoCliente = TxtCorreoCliente.getText();

        String cliente = controladorClientes.validarCliente(nombreCliente, rutCliente, celularCliente, correoCliente);

        if (cliente != null) {
            JOptionPane.showMessageDialog(null, cliente);
        } else {
            JOptionPane.showMessageDialog(null, "Cliente " + nombreCliente + " agregado correctamente");
            limpiarCampos();
        }

        listaClientes = controladorClientes.obtenerClientes();
        mostrarClientesEnTabla(listaClientes);
    }//GEN-LAST:event_BtnAgregarClienteActionPerformed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        String nombreProveedor = TxtNombreProveedor.getText();
        String empresaProveedor = TxtEmpresa.getText();
        String celularProveedor = TxtContactoProveedor.getText();
        String correoProveedor = TxtCorreoProveedor.getText();

        String proveedor = controladorProveedor.validarProveedor(nombreProveedor, empresaProveedor, celularProveedor, correoProveedor);

        if (proveedor != null) {
            JOptionPane.showMessageDialog(null, proveedor);
        } else {
            JOptionPane.showMessageDialog(null, "Proveedor " + nombreProveedor + " agregado correctamente");
            limpiarCampos();
        }

        listaProveedores = controladorProveedor.obtenerProveedores();
        mostrarProveedoresEnTabla(listaProveedores);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void BtnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarUsuarioActionPerformed
        // Validar los campos
        if (!validarCamposUsuarios()) {
            return;
        }

        // Obtener los datos de los campos
        String cargo = jComboBoxCargo.getSelectedItem().toString();
        String nombreUsuario = TxtNombreUsuario.getText();
        String rutUsuario = TxtRutUsuario.getText();
        String claveUsuario = TxtClaveUsuario.getText();
        String correoUsuario = TxtCorreoUsuario.getText();

        // Switch case para obtener id de cargo segun el nombre del cargo   
        int cargoInt = 0;
        switch (cargo) {
            case "Administrador":
                cargoInt = 1;
                break;
            case "Vendedor":
                cargoInt = 2;
                break;
            case "Bodega":
                cargoInt = 3;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Cargo no valido");
                return;
        }

        String usuario = controladorUsuarios.validarUsuario(cargoInt, nombreUsuario, rutUsuario, claveUsuario, correoUsuario);        

        if (usuario != null) {
            JOptionPane.showMessageDialog(null, usuario);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario " + nombreUsuario + " agregado correctamente");
            limpiarCampos();
        }

        listaUsuarios = controladorUsuarios.obtenerUsuarios();
        mostrarUsuariosEnTabla(listaUsuarios);
    }//GEN-LAST:event_BtnAgregarUsuarioActionPerformed

    // Eliminar cliente de la base de datos y de la tabbla
    private void BtnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClienteActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaListaClientes.getModel();
        
        // Obtener la fila seleccionada
        int fila = TablaRegistroClientes.getSelectedRow();
        System.out.println(fila);

        // Verificar si la fila es valida
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun cliente en la tabla");
            return;
        }
        
        // Eliminar el cliente de la base de datos
        try {
            if (fila != -1) {
                String rutCliente = TablaRegistroClientes.getValueAt(fila, 1).toString();
                
                // Crear objeto cliente
                Clientes cliente = new Clientes();
                cliente.setRut(rutCliente);
                
                // Eliminar el cliente de la base de datos
                controladorClientes.eliminarCliente(cliente);
                
                // Eliminar el cliente de la tabla
                modelo.removeRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el cliente " + e.getMessage());
        }

        listaClientes = controladorClientes.obtenerClientes();
        mostrarClientesEnTabla(listaClientes);
    }//GEN-LAST:event_BtnEliminarClienteActionPerformed

    private void BtnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUsuarioActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) TablaPersonal.getModel();
        
        // Obtener la fila seleccionada
        int fila = TablaPersonal.getSelectedRow();

        // Verificar si la fila es valida
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun usuario en la tabla");
            return;
        }   

        try {
            if (fila != -1) {
                int rutUsuario = Integer.parseInt(TablaPersonal.getValueAt(fila, 1).toString());

                // Crear objeto tipo usuario
                Usuarios usuario = new Usuarios();
                usuario.setRutUsuario(rutUsuario);

                // Eliminar usuario de la base de datos
                controladorUsuarios.eliminarUsuario(usuario);

                // Eliminar usuario de la tabla
                modelo.removeRow(fila);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario " + e.getMessage());
        }   
    }//GEN-LAST:event_BtnEliminarUsuarioActionPerformed

    private void BtnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarUsuarioActionPerformed
        // Validar los campos
        if (!validarCamposUsuarios()) {
            return;
        }

        // Obtener los datos de los campos
        String nombreUsuario = TxtNombreUsuario.getText();
        String rutUsuario = TxtRutUsuario.getText();
        String correoUsuario = TxtCorreoUsuario.getText();
        String cargoUsuario = jComboBoxCargo.getSelectedItem().toString();

        try {
            // Switch case para obtener id de cargo segun el nombre del cargo
            int cargoInt = 0;
            switch (cargoUsuario) {
                case "Administrador":
                    cargoInt = 1;
                    break;
                case "Bodeguero":
                    cargoInt = 2;
                    break;
                case "Vendedor":
                    cargoInt = 3;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Cargo no valido");
                    return;
            }
                
            // Crear objeto tipo usuario
            Usuarios usuario = new Usuarios();
            usuario.setRutUsuario(Integer.parseInt(rutUsuario));
            usuario.setNombre(nombreUsuario);
            usuario.setCorreo(correoUsuario);
            usuario.setId_cargo(cargoInt);

            // Modificar usuario de la base de datos
            controladorUsuarios.modificarUsuario(usuario);

            // Actualizar la lista de usuarios
            listaUsuarios = controladorUsuarios.obtenerUsuarios();
            mostrarUsuariosEnTabla(listaUsuarios);

            JOptionPane.showMessageDialog(null, "Usuario " + usuario.getNombre() + " modificado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar el usuario " + e.getMessage());
        }
    }//GEN-LAST:event_BtnModificarUsuarioActionPerformed

    private void BtnModificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarProveedorActionPerformed
        // Validar los campos
        if (!validarCamposProveedor()) {
            return;
        }

        // Obtener los datos de los campos
        String nombreProveedor = TxtNombreProveedor.getText();
        String empresaProveedor = TxtEmpresa.getText();
        String celularProveedor = TxtContactoProveedor.getText();
        String correoProveedor = TxtCorreoProveedor.getText();

        try {
            // Crear objeto tipo proveedor
            Proveedores proveedor = new Proveedores();  
            proveedor.setNombre(nombreProveedor);
            proveedor.setEmpresa(empresaProveedor);
            proveedor.setCelular(celularProveedor);
            proveedor.setCorreo(correoProveedor);

            // Modificar proveedor de la base de datos
            controladorProveedor.modificarProveedor(proveedor); 

            // Actualizar la lista de proveedores
            listaProveedores = controladorProveedor.obtenerProveedores();
            mostrarProveedoresEnTabla(listaProveedores);

            JOptionPane.showMessageDialog(null, "Proveedor " + proveedor.getNombre() + " modificado correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar el proveedor " + e.getMessage());
        }
        
    }//GEN-LAST:event_BtnModificarProveedorActionPerformed

    private void BtnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarProductoActionPerformed
        // pajas
        
    }//GEN-LAST:event_BtnModificarProductoActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // Crear el mensaje del reporte con Stringbuilder
        StringBuilder reporte = new StringBuilder();
        reporte.append("Cantidad de productos: " + listaProductos.size() + "\n");
        reporte.append("Cantidad de clientes: " + listaClientes.size() + "\n");
        reporte.append("Cantidad de proveedores: " + listaProveedores.size() + "\n");
        reporte.append("Cantidad de usuarios: " + listaUsuarios.size() + "\n");

        reporte.append("\n");
        reporte.append("Productos: \n");
        for (int i = 0; i < listaProductos.size(); i++) {
            reporte.append("Producto: " + listaProductos.get(i).getNombreProducto() + " - " + "Precio: " + listaProductos.get(i).getPrecio() + " - " + "Cantidad: " + listaProductos.get(i).getCantidad() + "\n");
        }

        reporte.append("\n");
        reporte.append("Clientes: \n");
        for (int i = 0; i < listaClientes.size(); i++) {
            reporte.append("Cliente: " + listaClientes.get(i).getNombre() + " - " + "Rut: " + listaClientes.get(i).getRut() + " - " + "Celular: " + listaClientes.get(i).getCelular() + " - " + "Correo: " + listaClientes.get(i).getCorreo() + "\n");
        }   

        reporte.append("\n");
        reporte.append("Proveedores: \n");
        for (int i = 0; i < listaProveedores.size(); i++) {
            reporte.append("Proveedor: " + listaProveedores.get(i).getNombre() + " - " + "Empresa: " + listaProveedores.get(i).getEmpresa() + " - " + "Celular: " + listaProveedores.get(i).getCelular() + " - " + "Correo: " + listaProveedores.get(i).getCorreo() + "\n");
        }

        reporte.append("\n");
        reporte.append("Usuarios: \n");
        for (int i = 0; i < listaUsuarios.size(); i++) {
            reporte.append("Usuario: " + listaUsuarios.get(i).getNombre() + " - " + "Rut: " + listaUsuarios.get(i).getRutUsuario() + " - " + "Correo: " + listaUsuarios.get(i).getCorreo() + " - " + "Cargo: " + listaUsuarios.get(i).getCargo() + "\n");
        }

        // Mostrar el reporte en una ventana JFRAME
        JFrame ventanaReporte = new JFrame("Reporte");
        ventanaReporte.setSize(600, 600);
        ventanaReporte.setLocationRelativeTo(null);
        ventanaReporte.setVisible(true);

        JTextArea txtAreaReporte = new JTextArea(reporte.toString());
        JScrollPane scrollPane = new JScrollPane(txtAreaReporte);
        ventanaReporte.add(scrollPane);

    }//GEN-LAST:event_btnReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladorUsuarios.cerrarSesion();
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProductoActionPerformed
        if (!validarCamposProductos()) {
            return;
        }
        
        try {
            String nombreProducto = TxtNombreProducto.getText();
            String precioProducto = TxtPrecioUnitario.getText();
            String cantidadProducto = TxtStockProducto.getText();
            String catergoriaStock = comboBoxStock.getSelectedItem().toString();
            
            String categoriaSeleccionada = "";
            switch (catergoriaStock) {
                case "Procesador":
                    categoriaSeleccionada = "1";
                    break;
                case "Placa Madre":
                    categoriaSeleccionada = "2";
                    break;
                case "Memoria RAM":
                    categoriaSeleccionada = "3";
                    break;
                case "Fuente de Poder":
                    categoriaSeleccionada = "4";
                    break;
                case "Gabinete":
                    categoriaSeleccionada = "5";
                    break;
            }

            // crear objeto tipo producto
            Productos producto = new Productos();
            producto.setNombreProducto(nombreProducto);
            producto.setPrecio(Integer.parseInt(precioProducto));
            producto.setCantidad(Integer.parseInt(cantidadProducto));
            producto.setCategoria(Integer.parseInt(categoriaSeleccionada));

            // Agregar el producto a la base de datos
            String productoControlador = controladorProductos.validarProducto(nombreProducto, precioProducto, cantidadProducto, catergoriaStock);
            if (productoControlador != null) {
                JOptionPane.showMessageDialog(null, productoControlador);
                limpiarCampos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al agregar el producto " + e.getMessage());
        }
        
        // Actualizar la tabla
        listaProductos = controladorProductos.obtenerProductos();
        mostrarProductosEnTabla(listaProductos);
    }//GEN-LAST:event_BtnAgregarProductoActionPerformed

    //Mostrar los datos en laabla de clientes
    public void mostrarClientesEnTabla(List<Clientes> listaClientes) {
        String matriz[][] = new String[listaClientes.size()][4];

        for (int i = 0; i < listaClientes.size(); i++) {
            matriz[i][0] = listaClientes.get(i).getNombre();
            matriz[i][1] = listaClientes.get(i).getRut();
            matriz[i][2] = String.valueOf(listaClientes.get(i).getCelular());
            matriz[i][3] = listaClientes.get(i).getCorreo();
        }
        TablaListaClientes.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Nombre", "Rut", "Celular", "Correo" }));
        TablaRegistroClientes.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Nombre", "Rut", "Celular", "Correo" }));
    }

    // Mostrard atos en la tabla proveedores
    public void mostrarProveedoresEnTabla(List<Proveedores> listaProveedores) {
        String matriz[][] = new String[listaProveedores.size()][4];

        for (int i = 0; i < listaProveedores.size(); i++) {
            matriz[i][0] = listaProveedores.get(i).getNombre();
            matriz[i][1] = listaProveedores.get(i).getEmpresa();
            matriz[i][2] = String.valueOf(listaProveedores.get(i).getCelular());
            matriz[i][3] = listaProveedores.get(i).getCorreo();
        }
        
        TablaListaProveedores.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Nombre", "Empresa", "Celular", "Correo" }));
        TablaRegistroProveedor.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Nombre", "Empresa", "Celular", "Correo" }));
    }

    // Mostrar datos en la tabla usuarios
    public void mostrarUsuariosEnTabla(List<Usuarios> listaUsuarios) {
        String matriz[][] = new String[listaUsuarios.size()][4];

        for (int i = 0; i < listaUsuarios.size(); i++) {
            matriz[i][0] = listaUsuarios.get(i).getNombre();
            matriz[i][1] = String.valueOf(listaUsuarios.get(i).getRutUsuario());
            matriz[i][2] = listaUsuarios.get(i).getCorreo();
            matriz[i][3] = listaUsuarios.get(i).getCargo();
        }

        TablaPersonal.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Nombre", "Rut", "Correo", "Cargo" }));
    }

    // Mostrar datos en la tabla productos
    public void mostrarProductosEnTabla(List<Productos> listaProductos) {
        String matriz[][] = new String[listaProductos.size()][4];

        for (int i = 0; i < listaProductos.size(); i++) {
            matriz[i][0] = listaProductos.get(i).getNombreProducto();
            matriz[i][1] = String.valueOf(listaProductos.get(i).getPrecio());
            matriz[i][2] = String.valueOf(listaProductos.get(i).getCategoria());
            matriz[i][3] = String.valueOf(listaProductos.get(i).getCantidad());
        }

        TablaProductos1.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[] { "Producto", "Precio", "Categoria", "Cantidad" }));
    }

    public void limpiarCampos() {
        TxtNombreProveedor.setText("");
        TxtEmpresa.setText("");
        TxtContactoProveedor.setText("");
        TxtCorreoProveedor.setText("");
        TxtCorreoUsuario.setText("");
        TxtNombreCliente.setText("");
        TxtRutCliente.setText("");
        TxtContactoCliente.setText("");
        TxtCorreoCliente.setText("");
    }

    // Funcion para vaalidar los campos
    public boolean validarCamposProveedor() {
        if (controlador.verificarCampoVacio(TxtNombreProveedor, "El campo nombre del proveedor esta vacio") &&
            controlador.verificarCampoVacio(TxtEmpresa, "El campo empresa del proveedor esta vacio") &&
            controlador.verificarCampoVacio(TxtContactoProveedor, "El campo contacto del proveedor esta vacio") &&
            controlador.verificarCampoVacio(TxtCorreoProveedor, "El campo correo del proveedor esta vacio")) {
            return true;
        }
        return false;
    }

    // Funcion para validar los campos de los productos
    public boolean validarCamposProductos() {
        if (controlador.verificarCampoVacio(TxtNombreProducto, "El campo nombre del producto esta vacio") &&
            controlador.verificarCampoVacio(TxtPrecio, "El campo precio del producto esta vacio") &&
            controlador.verificarCampoVacio(TxtCantidad, "El campo cantidad del producto esta vacio")) {
            return true;
        }
        return false;
    }

    // Funcion para validar los campos de los usuarios
    public boolean validarCamposUsuarios() {
        if (controlador.verificarCampoVacio(TxtNombreUsuario, "El campo nombre del usuario esta vacio") &&
            controlador.verificarCampoVacio(TxtRutUsuario, "El campo rut del usuario esta vacio") &&
            controlador.verificarCampoVacio(TxtCorreoUsuario, "El campo correo del usuario esta vacio")) {
            return true;
        }
        return false;
    }

    // Funcion para validar los campos de los clientes
    public boolean validarCamposClientes() {
        if (controlador.verificarCampoVacio(TxtNombreCliente, "El campo nombre del cliente esta vacio") &&
            controlador.verificarCampoVacio(TxtRutCliente, "El campo rut del cliente esta vacio") &&
            controlador.verificarCampoVacio(TxtContactoCliente, "El campo contacto del cliente esta vacio") &&
            controlador.verificarCampoVacio(TxtCorreoCliente, "El campo correo del cliente esta vacio")) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarCliente;
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JButton BtnAgregarUsuario;
    private javax.swing.JButton BtnAgregarVenta;
    private javax.swing.JButton BtnEliminarCliente;
    private javax.swing.JButton BtnEliminarProducto;
    private javax.swing.JButton BtnEliminarProveedor;
    private javax.swing.JButton BtnEliminarUsuario;
    private javax.swing.JButton BtnModificarCliente;
    private javax.swing.JButton BtnModificarProducto;
    private javax.swing.JButton BtnModificarProveedor;
    private javax.swing.JButton BtnModificarUsuario;
    private javax.swing.JComboBox<String> CBXFecha;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelCargo;
    private javax.swing.JLabel LabelContacto;
    private javax.swing.JLabel LabelContactoCliente;
    private javax.swing.JLabel LabelContactoProveedor;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelCorreoCliente;
    private javax.swing.JLabel LabelCorreoProveedor;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelEmpresa;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelIngresoProductos;
    private javax.swing.JLabel LabelNombreCliente;
    private javax.swing.JLabel LabelNombrePersonal;
    private javax.swing.JLabel LabelNombreProducto;
    private javax.swing.JLabel LabelNombreProveedores;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JLabel LabelPrecioUnitario;
    private javax.swing.JLabel LabelProducto;
    private javax.swing.JLabel LabelProveedor;
    private javax.swing.JLabel LabelRegistroClientes;
    private javax.swing.JLabel LabelRegistroDeVentas;
    private javax.swing.JLabel LabelRegistroProveedores;
    private javax.swing.JLabel LabelRut;
    private javax.swing.JLabel LabelStockProducto;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JScrollPane PanelListaDeClientes;
    private javax.swing.JPanel PanelPersonal;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelProveedores;
    private javax.swing.JPanel PanelRegistroDeVentas;
    private javax.swing.JPanel PanelTablaPersonal;
    private javax.swing.JScrollPane PanelTablaProductos;
    private javax.swing.JScrollPane PanelTablaProveedores;
    private javax.swing.JPanel Panelinicio;
    private javax.swing.JScrollPane ScrollTablaPersonal;
    private javax.swing.JScrollPane ScrollTablaProductos;
    private javax.swing.JScrollPane ScrollTablaProveedores;
    private javax.swing.JScrollPane ScrollTablaVentas;
    private javax.swing.JTable TablaListaClientes;
    private javax.swing.JTable TablaListaProveedores;
    private javax.swing.JTable TablaPersonal;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaProductos1;
    private javax.swing.JTable TablaRegistroClientes;
    private javax.swing.JTable TablaRegistroProveedor;
    private javax.swing.JTable TableVentas;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtClaveUsuario;
    private javax.swing.JTextField TxtContactoCliente;
    private javax.swing.JTextField TxtContactoProveedor;
    private javax.swing.JTextField TxtCorreoCliente;
    private javax.swing.JTextField TxtCorreoProveedor;
    private javax.swing.JTextField TxtCorreoUsuario;
    private javax.swing.JTextField TxtEmpresa;
    private javax.swing.JLabel TxtListaCliente;
    private javax.swing.JTextField TxtNombreCliente;
    private javax.swing.JTextField TxtNombreProducto;
    private javax.swing.JTextField TxtNombreProveedor;
    private javax.swing.JTextField TxtNombreUsuario;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtPrecioUnitario;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JLabel TxtProveedores;
    private javax.swing.JLabel TxtRegistroVentas;
    private javax.swing.JTextField TxtRutCliente;
    private javax.swing.JTextField TxtRutUsuario;
    private javax.swing.JTextField TxtStockProducto;
    private javax.swing.JLabel TxtTitulo;
    private javax.swing.JTabbedPane VistaAdministrador;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> comboBoxStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
